### PR TITLE
Wait for configurable seconds to let Marrmot containers to start up

### PR DESCRIPTION
**Pull request by sverhoeven**
Refs #303

<del>
For now I set it to 3 seconds.
I want to make the delay value configurable, but not sure how
1. Add delay arg to setup()
2. Add container_delay to ewatercycle.yaml

I prefer option 1, @Peter9192 which do you prefer?
</del>

Adds delay argument to Marrmot*.setup() with by 0 as default.

### CODE REVIEW

**Comment by Peter9192** [comment]
> I prefer option 1, @Peter9192 which do you prefer?

I agree. Is 3 seconds a good default? I think it might be.

**Comment by Peter9192** [comment]
> Is 3 seconds a good default? I think it might be.

On second thought, can we set the default option to be using whatever the default value is in grpc4bmi?

**Comment by sverhoeven** [comment]
Implemented setup arg, @Peter9192 can you have another look?

**Review by Peter9192 — APPROVED** [review]
Can't seem to change the status of the code smell to "wontfix" or something like that. However, it is a consequence of our design, so let's keep it as is.

**Comment by sverhoeven** [comment]
thanks for reviewing

**Pull request merged**
