### PR TITLE
Update outdated docs

### PR DESCRIPTION
**Pull request by sverhoeven**
Refs #350

TODO
* [x] docstrings
  * [x] forcings
  * [x] parameter sets
  * [x] models
* [x] user guide notebook
  * [x] until model run
  * [x] generate
  * [x] model run
* [x] example notebooks
  * [x] model specific, should be moved to docs/examples/plugins/<modelname>/*.ipynb similar to src/ewatercycle/plugins and tests/plugins
  * [x] forcing generate notebook: each model section should be move to  docs/examples/plugins/<modelname>/forcing.ipynb
  * [x] Irrigation.ipynb
* [x] ~~docs on how to add model~~ Do later in PR for #338
  * [ ] I am writing a new model
  * [ ] I already have my own model
* [x] hpc2cluster docs
* [x] show that specific model has more methods. Either by adding link to super class or showing inherited methods.

### CODE REVIEW

**Comment by sverhoeven** [comment]
@Peter9192 @BSchilperoort In the notebook we are printing objects. 
Pydantic models are printed as a long single line, which is not very user friendly.
We could use https://python-devtools.helpmanual.io/ or https://github.com/willmcgugan/rich or https://docs.python.org/3/library/pprint.html (+.dict()).

To me rich looks nicest in a notebook, which do you prefer or leave as is?

**Comment by BSchilperoort** [comment]
> @Peter9192 @BSchilperoort In the notebook we are printing objects. Pydantic models are printed as a long single line, which is not very user friendly. We could use https://python-devtools.helpmanual.io/ or https://github.com/willmcgugan/rich or https://docs.python.org/3/library/pprint.html (+.dict()).
> 
> To me rich looks nicest in a notebook, which do you prefer or leave as is?

The rich prints look good! It's also a very widely used package, so I see no reason why we wouldn't want to use it.

**Comment by Peter9192** [comment]
I've also used rich before, quite like it

**Comment by sverhoeven** [comment]
rich it is

**Comment by sverhoeven** [comment]
Notebooks where executed in a vagrant box 
* provisioned with https://github.com/eWaterCycle/infra 
* this branch installed with sudo.
* in /etc/ewatercycle.yaml, removed output_dir and pruned parameter sets, use apptainer 
* `ln -s /usr/bin/singularity /usr/bin/apptainer` as https://github.com/eWaterCycle/infra/pull/137 not merged yet.

**Comment by sverhoeven** [comment]
The wlfow `get_grid_shape()`  seems to return inverted order (x,y instead of y,x acco)  which is used to reserve numpy array. Causing things to not fit.

```
# bypass OptionalDestBmi and MemoizedBmi by calling origin.origin.
model_instance.bmi.origin.origin.get_grid_shape(1, np.empty((2,), dtype=np.float64))
array([169., 187.])
# Below works
model_instance.bmi.origin.origin.get_grid_x(1, np.empty((169,), dtype=np.float64))
model_instance.bmi.origin.origin.get_grid_y(1, np.empty((187,), dtype=np.float64))
# but OptionalDestBmi uses 187 for x and 169 for y, which fails.
```

We might needs some corrective bmi class in pyewatercycle that can swap result of `get_grid_shape()` or fix in container image, which might break other code.

**Comment by BSchilperoort** [comment]
> The wlfow `get_grid_shape()` seems to return inverted order (x,y instead of y,x acco) which is used to reserve numpy array. Causing things to not fit.

Looks like the problem occurs here:
https://github.com/openstreams/wflow/blob/bdc9b7966a0caa3c826b3a1f25150186b37d683f/wflow/wflow_bmi.py#L1182-L1197

The return statement should be
```py
return [dim[5], dim[4]]
```

Seeing as the old wflow is not being developed anymore, I would vote for the fix with the least amount of work. If it can be easily patched in this repo, that might be best.

**Comment by BSchilperoort** [comment]
I mentioned this issue during standup, and @SarahAlidoost pointed out that there was an old issue discussing the switched x/y coordinates: https://github.com/eWaterCycle/ewatercycle/issues/104

**Comment by sverhoeven** [comment]
Not all example notebooks have been run completely. So some old output is still there.

**Review by Peter9192 — APPROVED** [review]
This PR contains many good changes. We will need to do several more passes through the documentation as we're updating the model and forcing API, so I'm gonna approve this as so we can use is as a good basis for further improvements in follow-up PRs

**Pull request merged**
