### PR TITLE
Monster

### PR DESCRIPTION
**Pull request by Peter9192**
This branch combines #324, #334, and #339, and the first commit of #335. It can serve as a basis for further developing experimental changes in #335

### CODE REVIEW

**Comment by sverhoeven** [comment]
TODO
* [x] I made pytest and mypy green 
* [x] I reacted to all comments in https://github.com/eWaterCycle/ewatercycle/pull/324, https://github.com/eWaterCycle/ewatercycle/pull/334, and https://github.com/eWaterCycle/ewatercycle/pull/339 with changes committed here.
* [x] made branch use grpc4bmi>=0.4 
* [x] found some shortcomings while reviewing my own work, so I fixed those as well.

@Peter9192 can you have a look at the changes starting from https://github.com/eWaterCycle/ewatercycle/pull/340/commits/26a2f4490de2bd63cedfae43fdc482d40b61b5d0 ?

**Comment by Peter9192** [comment]
Awesome, everything green and works well! I'm happy with this:

image

Less happy with the new conflicts in my feature branches 😓 Can we merge this quickly?

**Comment by Peter9192** [comment]
@sverhoeven note that I can't approve this as I'm officially the author of this PR even though you did all of the work

**Review by sverhoeven — APPROVED** [review]
I approve on behalf of @Peter9192

**Comment by sverhoeven** [comment]
Please go ahead and merge

**Pull request merged**
