### PR TITLE
Add 2020.1.2 to wflow versions

### PR DESCRIPTION
**Pull request by sverhoeven**
Can be tested by installing this branch locally and running

```
singularity build singularity-images/ewatercycle-wflow-grpc4bmi_2020.1.2.sif docker://ewatercycle/wflow-grpc4bmi:2020.1.2
```

To prevent version warning when getting a wflow parameter set, add the version in ewatercycle.yaml.

### CODE REVIEW

**Comment by jeromaerts** [comment]
@sverhoeven The model loads and completes the model.setup() step. However the model does not complete initialization due to a possible GDAL_DATA environment variable error. 

From wflow log:
wf_netcdfio - ERROR - EPGS not converted correctly: EPSG:4326. Is the GDAL_DATA environment variable set correctly?

This error does not occur with wflow v.2020.1.1

**Comment by sverhoeven** [comment]
Hmm, I tried to run docs/examples/wflow.ipynb with Docker container and it works, but with singularity fails. Seems GDAL_DATA is set to `~/miniconda/...` (my conda env outside container), which is not available inside container and thus it fails. 

I hardcoded the GDAL_DATA and PROJ_LIB env in the Dockerfile. The new Docker image is available on Docker Hub and new sif file (ewatercycle-wflow-grpc4bmi_2020.1.2.sif) is on dcache.

Now docs/examples/wflow.ipynb works with singularity as well.
Can you try again?

**Comment by jeromaerts** [comment]
@sverhoeven This fix solved the issue. The scientific output looks good. However, the model.finalize() function does not work correctly.

 log:
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: Data source /nfs/home6/jaerts/hydromt_camels_brazil/ewatercycle_output/wflow_20211008_105657/run_default/outsum/RiverWidth.map(raster):
cannot be created"
	debug_error_string = "{"created":"@1633690743.219000811","description":"Error received from peer ipv6:[::1]:55743","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Exception calling application: Data source /nfs/home6/jaerts/hydromt_camels_brazil/ewatercycle_output/wflow_20211008_105657/run_default/outsum/RiverWidth.map(raster):\ncannot be created","grpc_status":2}"

Creating the "outsum" folder manually in the output directory and rerunning model.finalize() solves the issue. This could be a local permission error. For now I think the PR can be merged.

**Comment by sverhoeven** [comment]
@jeromaerts thanks for testing.
Can you create an issue for this `outsum/` problem? As possible workaround you could add `[API]\nRiverWidth = 2, m` to config and use `model.get_value_as_xarray('RiverWidth')` to get output data.

**Pull request merged**
