### PR TITLE
Apptainer support

### LINKED ISSUE #290: apptainer support
The open source version of singularity has been renamed to apptainer https://apptainer.org/.

The eWaterCycle system should support this version.
Things that could/should be done:

- [x] grpc4bmi should have BmiClientApptainer class
- [x] setup-apptainer GH action and apptainer-versions repo (https://github.com/eWaterCycle/setup-singularity/issues/6)
- [x] eWatercycle Python package should support apptainer
- [x] snellius should have apptainer installed. This must be done by the SURF system administrators.
- [x] App on SURF Research cloud should have apptainer installed
- [ ] ~DCache should have apptainer-images folder~ keep old dir name  
- [ ] ~Replace any singularity usage in notebooks/documentation with apptainer~ Will be done in #353

At the moment (24 jan 2022) the release of apptainer version 1.0.0 is imminent.

### PR DESCRIPTION
**Pull request by sverhoeven**
Fixes #290 

This PR does not mark singularity_dir as deprecated, this is done in #334

### CODE REVIEW

**Review by Peter9192 — APPROVED** [review]
This PR mostly renames stuff. Would be good to test it together with other recent changes in #334

**Comment by Peter9192** [comment]
Singularity still used a lot in examples and docs. Would be nice to update at some point

**Comment by Peter9192** [comment]
Note that I've made #340, which solves merge conflicts between this branch and #339

**Comment by sverhoeven** [comment]
> Singularity still used a lot in examples and docs. Would be nice to update at some point

Docs has singularity to clearify apptainer fork. 
The example notebooks now use apptainer, but they have not been run with that setup.

**Comment by Peter9192** [comment]
Merged as part of #340

**Pull request closed without merging**
