### PR TITLE
Replace Zenodo hardcoded description by description from GH release …

### LINKED ISSUE #197: In Zenodo record use description from release instead of .zenodo.json:decription
The Zenodo record at https://zenodo.org/record/5119390 now has one liner description instead of much better description at https://github.com/eWaterCycle/ewatercycle/releases/tag/1.0.0 . Can the description at GH release be used on Zenodo?

Also the title has a typo is a bit to short to be unique.

### PR DESCRIPTION
**Pull request by sverhoeven**
…+ Make Zenodo title more unique

Fixes #197

https://zenodo.org/record/5119390 has been updated to reflect changes in this PR.

### CODE REVIEW

**Comment by Peter9192** [comment]
So if there's no `description` field in the .zenodo.json file, then it will automatically fall back to the GH release info?

**Comment by Peter9192** [comment]
The markdown doesn't seem to render on the Zenodo homepage..

**Comment by bouweandela** [comment]
You might also want to add the ewatercycle project under `grants` and the `nlesc` under `communities`: https://developers.zenodo.org/#representation

**Comment by sverhoeven** [comment]
Rendering fixed.

**Comment by sverhoeven** [comment]
> So if there's no `description` field in the .zenodo.json file, then it will automatically fall back to the GH release info?

Yep, as each Zenodo record is a specific version having GH release info makes more sense to me then a hardcoded string.

**Review by Peter9192 — APPROVED** [review]

**Pull request merged**
