### PR TITLE
Added AbstractModel class

### LINKED ISSUE #33: Create model abstract class
Modelled after pymt and requirements of notebooks.

### PR DESCRIPTION
**Pull request by sverhoeven**
Fixes #33

Docs check fails, but should be solved in #31

### CODE REVIEW

**Review by Peter9192 — COMMENTED** [review]
Hey @sverhoeven cool stuff! I was wondering, what about stuff like 
```
grid_id = model.get_var_grid(variable)
shape = model.get_grid_shape(grid_id)
lon = model.get_grid_x(grid_id)
lat = model.get_grid_y(grid_id)
```
I couldn't find what we decided about that in the backlog item

**Comment by sverhoeven** [comment]
> Hey @sverhoeven cool stuff! I was wondering, what about stuff like
> 
> ```
> grid_id = model.get_var_grid(variable)
> shape = model.get_grid_shape(grid_id)
> lon = model.get_grid_x(grid_id)
> lat = model.get_grid_y(grid_id)
> ```
> 
> I couldn't find what we decided about that in the backlog item

I think those should not be public, instead the `get_as_xarray()` (#1460) or `run()` (#1459), they will internally use those bmi functions.

**Comment by Peter9192** [comment]
> I think those should not be public, instead the `get_as_xarray()` (#1460) or `run()` (#1459), they will internally use those bmi functions.

Okay! That's also fine with me 👍

**Review by Peter9192 — APPROVED** [review]
I guess the real test will follow once we start implementing concrete model classes.

**Comment by sverhoeven** [comment]
Thanks for reviewing

**Pull request merged**
