### PR TITLE
Fixes type checking notebooks errors

### LINKED ISSUE #262: Typechecking in notebooks ignores ewatercycle type errors
Currently
```shell
pre-commit run --all-files nbqa-mypy
```
says
```
nbqa-mypy................................................................Passed
```

Which is incorrect because some method arguments must be str and not the passed in Path objects.

It would be nice if type checking on notebooks was actually checking ewatercycle code.

### PR DESCRIPTION
**Pull request by sverhoeven**
Fixes #262 and fixes the errors that where reported

After notebook typechecking was enabled for ewatercycle package the following errors where found
```shell
pre-commit run --all-files nbqa-mypy
nbqa-mypy................................................................Failed
- hook id: nbqa-mypy
- exit code: 1

ewatercycle/util.py:8: error: Library stubs not installed for "dateutil.parser" (or incompatible with Python 3.9)
ewatercycle/util.py:8: note: Hint: "python3 -m pip install types-python-dateutil"
ewatercycle/util.py:8: note: (or run "mypy --install-types" to install all missing stub packages)
ewatercycle/util.py:8: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
docs/examples/generate_forcing.ipynb:cell_5:1: error: "DefaultForcing" has no attribute "netcdfinput"
docs/examples/generate_forcing.ipynb:cell_8:1: error: "DefaultForcing" has no attribute "temperatureNC"
docs/examples/generate_forcing.ipynb:cell_8:1: error: "DefaultForcing" has no attribute "precipitationNC"
docs/examples/generate_forcing.ipynb:cell_11:1: error: "DefaultForcing" has no attribute "PrefixTavg"
docs/examples/generate_forcing.ipynb:cell_11:1: error: "DefaultForcing" has no attribute "PrefixPrecipitation"
docs/user_guide.ipynb:cell_10:2: error: Argument "directory" to "load_foreign" has incompatible type "Path"; expected "str"
docs/user_guide.ipynb:cell_15:2: error: Argument "forcing" to "Wflow" has incompatible type "DefaultForcing"; expected "Optional[WflowForcing]"
docs/user_guide.ipynb:cell_26:4: error: Argument "station_id" to "get_grdc_data" has incompatible type "int"; expected "str"
docs/examples/lisflood.ipynb:cell_6:2: error: Argument "forcing" to "Lisflood" has incompatible type "DefaultForcing"; expected "LisfloodForcing"
docs/examples/MarrmotM01.ipynb:cell_5:1: error: Argument "forcing" to "MarrmotM01" has incompatible type "DefaultForcing"; expected "MarrmotForcing"
docs/examples/MarrmotM14.ipynb:cell_5:1: error: Argument "forcing" to "MarrmotM14" has incompatible type "DefaultForcing"; expected "MarrmotForcing"
docs/examples/wflow.ipynb:cell_4:2: error: Argument "directory" to "load_foreign" has incompatible type "Path"; expected "str"
docs/examples/wflow.ipynb:cell_6:2: error: Argument "forcing" to "Wflow" has incompatible type "DefaultForcing"; expected "Optional[WflowForcing]"
docs/examples/pcrglobwb.ipynb:cell_8:2: error: Argument "forcing" to "PCRGlobWB" has incompatible type "DefaultForcing"; expected "Optional[PCRGlobWBForcing]"
docs/examples/pcrglobwb.ipynb:cell_14:1: error: Value of type "Iterable[str]" is not indexable
```

This PR clears all errors so now you get
```shell
pre-commit run --all-files nbqa-mypy
nbqa-mypy................................................................Passed
```

Created https://github.com/eWaterCycle/ewatercycle/issues/263 to at some point re-enable forcing return types.

### CODE REVIEW

**Comment by sverhoeven** [comment]
Hmm I had an old ewatercycle folder in my installation, once removed then `pre-commit run --all-files nbqa-mypy` gave no errors. 

Checkout out https://github.com/eWaterCycle/ewatercycle/pull/258 branch raises them again when run outside pre-commit with

```shell
pip install nbqa
nbqa mypy docs/examples/MarrmotM01.ipynb
docs/examples/MarrmotM01.ipynb:cell_5:1: error: Argument "forcing" to "MarrmotM01" has incompatible type "DefaultForcing"; expected "MarrmotForcing"
Found 1 error in 1 file (checked 1 source file)
```
With pre-commit its reporting no problems
```
pre-commit run -a nbqa-mypy
nbqa-mypy................................................................Passed

```

**Comment by sverhoeven** [comment]
Seems setup.cfg has `ignore_missing_imports = True` which hides that running via pre-commit the ewatercycle package is not in search path. So effectively the notebook is only checked on local type and calls to imported methods are ignored.

I need to add `src/ewatercycle/__init__.py` to search path so mypy can check types for things imported from ewatercycle package. This can be done with
```
MYPYPATH=src pre-commit run --all-files nbqa-mypy
```
But that is not a nice solution as its hard to automate. Luckily it can also be added to setup.cfg as [mypy_path](https://mypy.readthedocs.io/en/stable/config_file.html#confval-mypy_path).

**Comment by sverhoeven** [comment]
Now errors are
```
pre-commit run --all-files nbqa-mypy
nbqa-mypy................................................................Failed
- hook id: nbqa-mypy
- exit code: 1

docs/examples/generate_forcing.ipynb:cell_5:1: error: "DefaultForcing" has no attribute "netcdfinput"
docs/examples/generate_forcing.ipynb:cell_8:1: error: "DefaultForcing" has no attribute "temperatureNC"
docs/examples/generate_forcing.ipynb:cell_8:1: error: "DefaultForcing" has no attribute "precipitationNC"
docs/examples/generate_forcing.ipynb:cell_11:1: error: "DefaultForcing" has no attribute "PrefixTavg"
docs/examples/generate_forcing.ipynb:cell_11:1: error: "DefaultForcing" has no attribute "PrefixPrecipitation"
docs/user_guide.ipynb:cell_15:2: error: Argument "forcing" to "Wflow" has incompatible type "DefaultForcing"; expected "Optional[WflowForcing]"
docs/examples/lisflood.ipynb:cell_6:2: error: Argument "forcing" to "Lisflood" has incompatible type "DefaultForcing"; expected "LisfloodForcing"
docs/examples/MarrmotM01.ipynb:cell_5:1: error: Argument "forcing" to "MarrmotM01" has incompatible type "DefaultForcing"; expected "MarrmotForcing"
docs/examples/MarrmotM14.ipynb:cell_5:1: error: Argument "forcing" to "MarrmotM14" has incompatible type "DefaultForcing"; expected "MarrmotForcing"
docs/examples/wflow.ipynb:cell_6:2: error: Argument "forcing" to "Wflow" has incompatible type "DefaultForcing"; expected "Optional[WflowForcing]"
docs/examples/pcrglobwb.ipynb:cell_8:2: error: Argument "forcing" to "PCRGlobWB" has incompatible type "DefaultForcing"; expected "Optional[PCRGlobWBForcing]"
Found 11 errors in 7 files (checked 8 source files)

```

**Review by Peter9192 — APPROVED** [review]
Confirm it triggers type errors when introduced. This PR removes all type errors, so check passes.

**Pull request merged**
